language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - gemfiles/4.0.0.gemfile
  - gemfiles/4.0.1.gemfile
  - gemfiles/4.0.2.gemfile
  - gemfiles/4.0.3.gemfile
  - gemfiles/4.0.4.gemfile
  - gemfiles/4.1.0.gemfile
script: 'bundle exec rake'
